"""empty message

Revision ID: a9efb6712b2e
Revises: 
Create Date: 2021-11-02 10:20:54.345547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9efb6712b2e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('volume',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('volumeId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['volumeId'], ['volume.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chapter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.Column('subtext', sa.String(length=45), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('bookId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bookId'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=45), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('bookId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bookId'], ['chapter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verse')
    op.drop_table('chapter')
    op.drop_table('book')
    op.drop_table('volume')
    # ### end Alembic commands ###
